# Generated by Django 3.2.16 on 2022-11-20 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_auto_20221120_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='name',
        ),
    ]
